### ISSUE TITLE
interop: meta-issue

### ISSUE THREAD

**Issue by stepancheg** [stepancheg/grpc-rust#47]
cc @stevej

- [x] `empty_unary` empty (zero bytes) request and response.
- [ ] `large_unary` single request and (large) response. #39
- [x] `client_streaming` request streaming with single response.
- [ ] `server_streaming` single request with response streaming. #41
- [x] `ping_pong` full-duplex streaming.
- [x] `empty_stream` full-duplex streaming with zero message.
- [x] `timeout_on_sleeping_server` fullduplex streaming on a sleeping server.
- [ ] `compute_engine_creds` large_unary with compute engine auth. (needs TLS)
- [ ] `service_account_creds` large_unary with service account auth. (needs TLS)
- [ ] `jwt_token_creds` large_unary with jwt token auth. (needs TLS)
- [ ] `per_rpc_creds` large_unary with per rpc token. (needs TLS)
- [ ] `oauth2_auth_token` large_unary with oauth2 token auth. (needs TLS)
- [x] `cancel_after_begin` cancellation after metadata has been sent but before payloads are sent.
- [x] `cancel_after_first_response` cancellation after receiving 1st message from the server.
- [ ] `status_code_and_message` status code propagated back to client. #42
- [ ] `custom_metadata` server will echo custom metadata. #43
- [ ] `unimplemented_method` client attempts to call unimplemented method. #44
- [ ] `unimplemented_service` client attempts to call unimplemented service. (default "large_unary") #45
